
// Announcments

export const GET_ANNOUNCMNTS = "GET_ANNOUNCMNTS";

// Common

export const SET_LANG = "SET_LANG";


// Users

export const REGISTER_USER = "REGISTER_USER";
export const SET_SIGNUP_PROCESS = "SET_SIGNUP_PROCESS";
export const SET_SIGNUP_STATUS = "SET_SIGNUP_STATUS";
export const SET_LOGIN_PROCESS = "SET_LOGIN_PROCESS";
export const SET_LOGIN_STATUS = "SET_LOGIN_STATUS";
export const SET_USER_DATA = "SET_USER_DATA";
export const SET_USER_DATA_MANUAL = "SET_USER_DATA_MANUAL";
export const SET_OTPSEND_PROCESS = "SET_OTPSEND_PROCESS";
export const SET_OTPSEND_STATUS = "SET_OTPSEND_STATUS";
export const SET_OTPVERFY_STATUS = "SET_OTPVERFY_STATUS";
export const SET_OTPVERFY_STATUS_ONCE = "SET_OTPVERFY_STATUS_ONCE";
export const SET_OTPVERFY_PROCESS = "SET_OTPVERFY_PROCESS";
export const SET_CHANGEPASS_PROCESS = "SET_CHANGEPASS_PROCESS";
export const SET_TOKEN = "SET_TOKEN";
export const SET_CHNAGPASS_STATUS = "SET_CHNAGPASS_STATUS";
export const SET_CHNAGPASS_STATUS_ONCE = "SET_CHNAGPASS_STATUS_ONCE";
export const SET_LOGOUT = "SET_LOGOUT";


// Categories
export const SET_LOAD_CAT_PROCESS = "SET_LOAD_CAT_PROCESS";
export const SET_LOAD_CAT_STATUS = "SET_LOAD_CAT_STATUS";
export const SET_LOAD_CAT_DATA = "SET_LOAD_CAT_DATA";


// Products
export const SET_LOAD_PROD_PROCESS = "SET_LOAD_PROD_PROCESS";
export const SET_LOAD_PROD_STATUS = "SET_LOAD_PROD_STATUS";
export const SET_LOAD_PROD_DATA = "SET_LOAD_PROD_DATA";


// Favorites
export const SET_LOAD_FAV_PROCESS = "SET_LOAD_FAV_PROCESS";
export const SET_LOAD_FAV_STATUS = "SET_LOAD_FAV_STATUS";
export const SET_LOAD_FAV_DATA = "SET_LOAD_FAV_DATA";

// Address
export const SET_LOAD_ADDRESS_PROCESS = "SET_LOAD_ADDRESS_PROCESS";
export const SET_LOAD_ADDRESS_STATUS = "SET_LOAD_ADDRESS_STATUS";
export const SET_ADD_ADDRESS = "SET_ADD_ADDRESS";
export const UPDATE_ADDRESS = "UPDATE_ADDRESS";
export const SET_LOAD_ADDRESS = "SET_LOAD_ADDRESS";


// Orders
export const SET_LOAD_ORDERS_PROCESS = "SET_LOAD_ORDERS_PROCESS";
export const SET_LOAD_ORDERS_STATUS = "SET_LOAD_ORDERS_STATUS";
export const SET_ADD_ORDERS = "SET_ADD_ORDERS";
export const SET_LOAD_ORDERS = "SET_LOAD_ORDERS";
export const SET_LOAD_BUYAGAIN = "SET_LOAD_BUYAGAIN";


// CARTorites
export const SET_LOAD_CART_PROCESS = "SET_LOAD_CART_PROCESS";
export const SET_LOAD_CART_STATUS = "SET_LOAD_CART_STATUS";
export const CLEAR_CART = "CLEAR_CART";
export const SET_LOAD_CART_DATA = "SET_LOAD_CART_DATA";
export const ADD_TO_CART = "ADD_TO_CART";
export const ADD_NEW_CART = "ADD_NEW_CART";
export const UPDATE_CART = "UPDATE_CART";
export const DEL_CART_ITEM = "DEL_CART_ITEM";


export const RESET_DATA = "RESET_DATA";







