export const constants = {
    en: {
        errors: {
            emailRequired: "Email id is required.",
            invalidEmail: "Please enter a valid email address.",
            passwordRequired: "Password is required.",
            passwordmin: "Password should have atleast 6 characters.",
            companyNamereq: "Compnay name is required.",
            phonereq: "Phone number is required.",
            phoneinvalid: "Please enter valid phone number",
            cnfPass: "Confirm password is required.",
            passNotsame: "Passwords not matched.",
            acpectTerms: "Please accept terms and conditions.",
            regNum: "Registration number or Entity bumber is required.",
            fulladdr: "Your complete address required.",
            addr1: "Address line is required",
            addrReq: "Address is required",
            prodReq: "Product name is required",
            qtyReq: "Quantity is required",
            priceReq: "Price required",
            descReq: "Description  is required",
            namereq: "Name  is required",
            swwptast: "Something went wrong, Please try after some time.",
            oops: "Oops",
            ok: "ok",
            pltapiyc: "Please login to add products in your cart.",
            loginReq: "Login Required!",
            cancel: "cancel",
            lgn: "login",
            pltaptf: "Please login to add product to favourite",
            insper: 'Insufficient permissions!',
            yntgcptuta: 'You need to grant camera permissions to use this app.',
            failed: "Failed",
            wcaaptas: "We coudn't add address please try after sometime.",
            ptalwd: "Permission to access location was denied",
            wcuypptas: "We coudn't update your profile please try after sometime."
        },
        static: {
            skip: "SKIP",
            email: "Email",
            pass: "Password",
            ivusp: "Invalid Username or password",
            singin: "Sign In",
            singup: "Sign Up",
            forpass: "Forgot Password?",
            or: "or",
            dhac: "Don’t have an account?",
            chtr: "Click Here to Register",
            companyName: "Company Name",
            mobileno: "Mobile Number",
            newpass: "New Password",
            cnfpass: 'Confirm Password',
            rnoen: 'Registration Number or Entity Number',
            iatc: " I Accept terms & conditions",
            pleasewait: "Please wait...",
            vrfcd: "Verify Code",
            pevc: "Please enter the verification code sent to mobile number: ",
            next: "Next",
            avcwbste: "A verification code will be sent to the email address. Please verify your email by entering the code on the next screen.",
            submit: "Submit",
            chngpass: "Change Password",
            ynpmbd: "Your new password must be different from previous used passwords.",
            ycie: "Your cart is empty.",
            chtmyd: "Click here to manage your address",
            vat: "Vat",
            payamt: "Payable Amount",
            cod: "COD",
            qty: "Qty",
            total: "Total",
            subtotal: "Sub Total",
            delChag: "Delivery charges",
            curr: "SAR",
            cart: "Cart",
            checkout: "Checkout",
            npf: "No products found",
            favourites: "Favourites",
            buyagain: "Buy Again",
            ydhafp: "You dont have any favorite products.",
            yhbap: "You haven't bought any product.",
            lfs: "Looking for something",
            cyistyco: "Complete your information so that you can order",
            favCap: "FAVOURITES",
            viewAll: "VIEW ALL",
            buyagaincap: "BUY AGAIN",
            categor: "CATEGORIES",
            dyhaso: "Do you have a Special Order?",
            clickHere: "Click Here",
            etsp: "Enter the Special Order",
            information: "Information",
            productname: "Product Name",
            quantity: "Quantity",
            expprc: "Expected Price",
            description: "Description",
            uapdo: "Upload a Photo / Doc (optional)",
            send: "Send",
            pls: "Please",
            lgn: "login",
            tayi: "to access your invoices",
            tayp: "to access your profile",
            download: "Download",
            home: "Home",
            Invoice: "Invoice",
            Profile: "Profile",
            cusaddr: "Customer Address",
            ydbie: "Your address book is empty",
            paymet: "Payment Method",
            summary: "Summary",
            done: "Done",
            sos: 'Special order sent',
            ysostm: 'Your special order sent to medshafy.',
            Brand: "Brand",
            modelNumber: "Model Number ",
            Country: "Country",
            anaddr: "Add New Address",
            compaddr: "Complete Address",
            name: 'Name',
            saveAddr: "Save Address",
            selDlo: "Select Delivery Location",
            alOpt: "Address line (Optional)",
            cnfLoc: "Confirm Location",
            Address: "Address",
            delyAddress: "Delivery Address",
            saveChanges: "Save Changes",
            yabie: "Your Address Book is Empty",
            sdttyl: "Start adding them to your list",
            myOrds: "My Orders",
            ydhaords: "Your dont have any orders.",
            ordTtl: "Order Total",
            pendorDel: "Pending for Delivery",
            ordPrc: "Processing",
            outofordel: "Out for delivery",
            delivered: "Delivered",
            cancelled: "Cancelled",
            Refunded: "Refunded",
            viewProds: "View Products",
            pbap: "Paid by Apple Pay",
            editprofil: "Edit Profile",
            buissName: "Business Name",
            EnoRn: "Entity Number or Register Number",
            NIF: "No Images Found",
            MyPrf: "My Profile",
            Photos: "Photos",
            myAccount: "My Account",
            category: "Category",
            results: "results",
            for: "for",
            chosqty: "Choose an Option...",
            single: "Single",
            AdrBk: "Address Book",
            favPros: "Favourite Products",
            Logout: "Logout",
            chosQtyPlace: "Choose Quantity",
            addToCart: "Add to cart",
            viewDetails: "View Details",
            language: "language",
            Privacy_Policy: "Privacy Policy",
            Terms_Conds: "Terms & Conditions"
        }
    },
    ar: {
        errors: {
            emailRequired: "مطلوب معرف البريد الإلكتروني.",
            invalidEmail: "محتاجين بريد إلكتروني صحيح",
            passwordRequired: "يرجى إدخال رقم سري",
            passwordmin: "يرجى إدخال رقم سري مكون من 6 خانات أو اكثر",
            companyNamereq: "محتاجين اسم المنشأة او المركز",
            phonereq: "محتاجين رقم جوالك",
            phoneinvalid: "يرجى إدخال رقم هاتف صحيح",
            cnfPass: "محتاجين تأكيد للرقم السري",
            passNotsame: "الرقم السري غير متطابق",
            acpectTerms: "الرجاء قبول الشروط والأحكام.",
            regNum: "محتاجين رقم سجلك التجاري (للتحقق)",
            fulladdr: "محتاجين عنوانك الوطني الكامل",
            addr1: "العنوان مطلوب",
            addrReq: "عنوانك الكامل مطلوب",
            prodReq: "أسم المنتج مطلوب",
            qtyReq: "الرجاء تحديد الكمية",
            priceReq: "الرجاء تحديد السعر المتوقع",
            descReq: "الرجاء وصف الطلب",
            namereq: "الاسم مطلوب",
            swwptast: "حصل خطأ ما , الرجاء المحاولة مرة أخرى",
            oops: "حصل خطأ ما , الرجاء المحاولة مرة أخرى",
            ok: "تمام",
            pltapiyc: "الرجاء تسجيل الدخول لإضافة منتجات في عربة التسوق الخاصة بك.",
            loginReq: "الرجاء تسجيل الدخول",
            cancel: "إلغـــاء",
            lgn: "تسجيل الدخول",
            pltaptf: "الرجاء تسجيل الدخول لإضافة المنتج إلى المفضلة",
            insper: "لايوجد صلاحية",
            yntgcptuta: "تحتاج إلى منح صلاحيات الكاميرا لاستخدام هذا التطبيق.",
            failed: "فشل",
            wcaaptas: "لم نستطيع إضافة العنوان الرجاء المحاولة لا حقاً",
            ptalwd: "تم رفض صلاحية الوصول لتحديد الموقع",
            wcuypptas: "لم نستطيع تحديث ملفك الشخصي الرجاء المحاولة لا حقاً",
        },
        static: {
            skip: "تخطي",
            email: "البريد الاكتروني",
            pass: "الرقم السري",
            ivusp: "خطأ في اسم المستخدم أو كلمة مرور",
            singin: "تسجيل الدخول",
            singup: "تسجيل جديد",
            forpass: "هل نسيت الرقم السري؟",
            or: " او",
            dhac: "ليس لديك حساب؟",
            chtr: "أشترك الآن",
            companyName: " أسم المنشأة",
            mobileno: "رقم الجوال للتواصل",
            newpass: "الرقم السري الجديد",
            cnfpass: "تأكيد الرقم السري",
            rnoen: "رقم السجل التجاري ",
            iatc: "الموافقة على شروط الاستخدام وسياسة الخصوصية",
            pleasewait: "الرجاء الانتظار",
            vrfcd: "التحقق من الكود",
            pevc: "الرجاء التحقق من الرمز المرسل الى جوالك",
            next: "التالي",
            avcwbste: "سيتم إرسال رمز التحقق إلى عنوان البريد الإلكتروني ",
            submit: "موافق",
            chngpass: "تغير الرقم السري",
            ynpmbd: "يجب ان تكون كلمة المرور مختلفة عن كلمة المرور السابقة",
            ycie: "سلة الشراء فارغة",
            chtmyd: "لإدارة عنوانك",
            vat: "ضريبة القيمة المضافة",
            payamt: "المبلغ قبل الضريبة",
            cod: "الدفع عند الأستلام",
            qty: "الكمية",
            total: "الاجمالي",
            subtotal: "المجموع",
            delChag: " قيمة التوصيل",
            curr: "ريال سعودي",
            cart: "السلة",
            checkout: "الدفع",
            npf: "المنتج غير متوفر",
            favourites: "المفضلة",
            buyagain: "اعادة الشراء",
            ydhafp: "لا يوجد لديك منتجات مفضلة",
            yhbap: "لايوجد لديك مشتريات",
            lfs: "محتاج مساعدة؟",
            cyistyco: " أكمل معلوماتك لتتمكن من الطلب",
            favCap: "المفضلة",
            viewAll: "عرض الكل",
            buyagaincap: "اعادة الشراء",
            categor: "التصنيفات",
            dyhaso: "عند طلبات خاصة",
            clickHere: "أضغط هنا",
            etsp: "أكتب طلبك الخاص",
            information: "معلومات",
            productname: "اسم المنتج",
            quantity: "الكمية",
            expprc: "السعر المتوقع",
            description: "أضف تفاصيل للطلب",
            uapdo: "رفع الصور / ملف ( أختياري)",
            send: "ارسال",
            pls: "رجاء",
            lgn: "login",
            tayi: "للوصول الى فواتيرك",
            tayp: "للوصول الى ملفك",
            download: "تنزيل",
            home: "الواجهة الرئيسية",
            Invoice: "الفاتورة",
            Profile: "الملف الشخصي",
            cusaddr: "عنوانك",
            ydbie: "ليس لديك عنوان مسجل",
            paymet: "طريقة الدفع",
            summary: "ملخص الطلب",
            done: "تم",
            sos: "تم ارسال طلبك الخاص",
            ysostm: "تم ارسال طلبك الخاص",
            Brand: "الماركة",
            modelNumber: "رقم الموديل",
            Country: "بلد الصنع",
            anaddr: "أضافة عنوان جديد",
            compaddr: "أكمل العنوان",
            name: "الاسم",
            saveAddr: "أحفظ العنوان",
            selDlo: "اختار عنوان التوصيل",
            alOpt: "وصف للعنوان (بجانب المسجد )",
            cnfLoc: "تأكيد الموقع",
            Address: "العنوان",
            delyAddress: "عنوان التوصيل",
            saveChanges: "حفظ التغييرات",
            yabie: "لم تقم بإضافة عنوان",
            sdttyl: "ابدأ اضافة المنتجات الى السلة",
            myOrds: "طلباتي",
            ydhaords: "ليس لديك طلبات",
            ordTtl: "أجمالي الطلبات",
            pendorDel: "طلباتك قيد المعالجة",
            ordPrc: "يعالج",
            outofordel: "خارج للتوصيل",
            delivered: "تم التوصيل",
            cancelled: "ألغيت",
            Refunded: "معاد",
            viewProds: "مشاهدة المنتجات",
            pbap: "الدفع عن طريق Apple Pay",
            editprofil: "تعديل الملف",
            buissName: "أسم المنشأة",
            EnoRn: "رقم السجل التجاري ",
            NIF: "لايوجد صورة",
            MyPrf: "الملف الشخصي",
            Photos: "صور السجل التجاري او لوحة المحل",
            myAccount: "حسابي",
            category: "قسم",
            results: "نتيجه",
            for: "لأجل",
            chosqty: "إختر خيار",
            single: "غير مرتبطة",
            AdrBk: "دليل العناوين",
            favPros: "المنتجات المفضلة",
            Logout: "تسجيل خروج",
            chosQtyPlace: "اختر الكمية",
            addToCart: "أضف إلى السلة",
            viewDetails: "عرض التفاصيل",
            language: "لغة",
            Privacy_Policy: "Privacy Policy",
            Terms_Conds: "Terms & Conditions"
        }
    }
}