export const constants = {
    en: {
        errors: {
            emailRequired: "Email id is required.",
            invalidEmail: "Please enter a valid email address.",
            passwordRequired: "Password is required.",
            passwordmin: "Password should have atleast 6 characters.",
            companyNamereq: "Compnay name is required.",
            phonereq: "Phone number is required.",
            phoneinvalid: "Please enter valid phone number",
            cnfPass: "Confirm password is required.",
            passNotsame: "Passwords not matched.",
            acpectTerms: "Please accept terms and conditions.",
            regNum: "Registration number or Entity bumber is required.",
            fulladdr: "Your complete address required.",
            addr1: "Address line is required",
            addrReq: "Address is required",
            prodReq: "Product name is required",
            qtyReq: "Quantity is required",
            priceReq: "Price required",
            descReq: "Description  is required",
            namereq: "Name  is required",
        },
        static: {
            skip: "SKIP",
            email: "Email",
            pass: "Password",
            ivusp: "Invalid Username or password",
            singin: "Sign In",
            singup: "Sign Up",
            forpass: "Forgot Password?",
            or: "or",
            dhac: "Don’t have an account?",
            chtr: "Click Here to Register",
            companyName: "Company Name",
            mobileno: "Mobile Number",
            newpass: "New Password",
            cnfpass: 'Confirm Password',
            rnoen: 'Registration Number or Entity Number',
            iatc: " I Accept terms & conditions",
            pleasewait: "Please wait...",
            vrfcd: "Verify Code",
            pevc: "Please enter the verification code sent to mobile number: ",
            next: "Next",
            forpass: "Forgot Password",
            avcwbste: "A verification code will be sent to the email address. Please verify your email by entering the code on the next screen.",
            submit: "Submit",
            chngpass: "Change Password",
            ynpmbd: "Your new password must be different from previous used passwords.",
            ycie: "Your cart is empty.",
            chtmyd: "Click here to manage your address",
            vat: "Vat",
            payamt: "Payable Amount",
            cod: "COD",
            qty: "Qty",
            total: "Total",
            subtotal: "Sub Total",
            delChag: "Delivery charges",
            curr: "SAR",
            cart: "Cart",
            checkout: "Checkout",
            npf: "No products found",
            favourites: "Favourites",
            buyagain: "Buy Again",
            ydhafp: "You dont have any favorite products.",
            yhbap: "You haven't bought any product.",
            lfs: "Looking for something",
            cyistyco: "Complete your information so that you can order",
            favCap: "FAVOURITES",
            viewAll: "VIEW ALL",
            buyagaincap: "BUY AGAIN",
            categor: "CATEGORIES",
            dyhaso: "Do you have a Special Order?",
            clickHere: "Click Here",
            etsp: "Enter the Special Order",
            information: "Information",
            productname: "Product Name",
            quantity: "Quantity",
            expprc: "Expected Price",
            description: "Description",
            uapdo: "Upload a Photo / Doc (optional)",
            send: "Send",
            pls: "Please",
            lgn: "login",
            tayi: "to access your invoices",
            download: "Download",
            home: "Home",
            Invoice: "Invoice",
            Profile: "Profile"
        }
    }
}